# Generated by Django 3.1.1 on 2020-11-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201031_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
