# Generated by Django 3.1.1 on 2020-11-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='', max_length=64),
        ),
    ]
