# Generated by Django 3.1.1 on 2020-11-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201101_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Unsorted', max_length=16),
        ),
    ]
