# Generated by Django 3.1.1 on 2020-11-02 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201102_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='high_bidder',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_winning', to=settings.AUTH_USER_MODEL),
        ),
    ]
