# Generated by Django 3.1.1 on 2020-11-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201102_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
